0.15.2: Missing header <algorithm>
>utils/directory_events.cc:118:40: error: no member named 'find_if' in namespace 'std'; did you mean '__find_if'?
>  118 |     wd_list::const_iterator itr = std::find_if(m_wd_list.begin(), m_wd_list.end(),
>      |                                   ~~~~~^~~~~~~
>      |                                        __find_if

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>